// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOiANlNi9mtsb_lUBAFMYHoqzH8L1k5aw',
    appId: '1:418768010568:web:3f83952278b46f287d477d',
    messagingSenderId: '418768010568',
    projectId: 'heed-38138',
    authDomain: 'heed-38138.firebaseapp.com',
    storageBucket: 'heed-38138.firebasestorage.app',
    measurementId: 'G-NQG2JBGDN4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL2cpSrMqeO8-jzDMSfphJLfsBlpVsUAM',
    appId: '1:418768010568:ios:8d1a59e924bdd7f07d477d',
    messagingSenderId: '418768010568',
    projectId: 'heed-38138',
    storageBucket: 'heed-38138.firebasestorage.app',
    iosBundleId: 'com.example.heed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOiANlNi9mtsb_lUBAFMYHoqzH8L1k5aw',
    appId: '1:418768010568:web:4a04bb5158dd169d7d477d',
    messagingSenderId: '418768010568',
    projectId: 'heed-38138',
    authDomain: 'heed-38138.firebaseapp.com',
    storageBucket: 'heed-38138.firebasestorage.app',
    measurementId: 'G-L413TFQRD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2p3SaVa3H4KuAfh0u-UoVhHi-4XCj4I',
    appId: '1:418768010568:android:b35ecea4da577fe87d477d',
    messagingSenderId: '418768010568',
    projectId: 'heed-38138',
    storageBucket: 'heed-38138.firebasestorage.app',
  );

}