import 'package:flutter/material.dart'; // <--- This MUST be here
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by the CLI
import 'app.dart';
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const HeedApp());
}